/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GarantiaRouteImport } from './routes/garantia'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BusinessInfoRouteImport } from './routes/business-info'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanosIndexRouteImport } from './routes/planos.index'
import { Route as DevIndexRouteImport } from './routes/dev.index'
import { Route as ProjetoIdRouteImport } from './routes/projeto.$id'
import { Route as PlanosSlugRouteImport } from './routes/planos.$slug'
import { Route as LeadIdRouteImport } from './routes/lead.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DevModelosIndexRouteImport } from './routes/dev.modelos.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as DevModelosSlugRouteImport } from './routes/dev.modelos.$slug'
import { Route as ApiPublicNotifyAdminSignupRouteImport } from './routes/api/public/notify-admin-signup'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiaRoute = GarantiaRouteImport.update({
  id: '/garantia',
  path: '/garantia',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessInfoRoute = BusinessInfoRouteImport.update({
  id: '/business-info',
  path: '/business-info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosIndexRoute = PlanosIndexRouteImport.update({
  id: '/planos/',
  path: '/planos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoIdRoute = ProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosSlugRoute = PlanosSlugRouteImport.update({
  id: '/planos/$slug',
  path: '/planos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadIdRoute = LeadIdRouteImport.update({
  id: '/lead/$id',
  path: '/lead/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DevModelosIndexRoute = DevModelosIndexRouteImport.update({
  id: '/dev/modelos/',
  path: '/dev/modelos/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const DevModelosSlugRoute = DevModelosSlugRouteImport.update({
  id: '/dev/modelos/$slug',
  path: '/dev/modelos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyAdminSignupRoute =
  ApiPublicNotifyAdminSignupRouteImport.update({
    id: '/api/public/notify-admin-signup',
    path: '/api/public/notify-admin-signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-info': typeof BusinessInfoRoute
  '/checkout': typeof CheckoutRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/comparar': typeof CompararRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRoute
  '/garantia': typeof GarantiaRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/painel': typeof PainelRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lead/$id': typeof LeadIdRoute
  '/planos/$slug': typeof PlanosSlugRoute
  '/projeto/$id': typeof ProjetoIdRoute
  '/dev/': typeof DevIndexRoute
  '/planos/': typeof PlanosIndexRoute
  '/api/public/notify-admin-signup': typeof ApiPublicNotifyAdminSignupRoute
  '/dev/modelos/$slug': typeof DevModelosSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dev/modelos/': typeof DevModelosIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-info': typeof BusinessInfoRoute
  '/checkout': typeof CheckoutRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/comparar': typeof CompararRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRoute
  '/garantia': typeof GarantiaRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/painel': typeof PainelRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lead/$id': typeof LeadIdRoute
  '/planos/$slug': typeof PlanosSlugRoute
  '/projeto/$id': typeof ProjetoIdRoute
  '/dev': typeof DevIndexRoute
  '/planos': typeof PlanosIndexRoute
  '/api/public/notify-admin-signup': typeof ApiPublicNotifyAdminSignupRoute
  '/dev/modelos/$slug': typeof DevModelosSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dev/modelos': typeof DevModelosIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-info': typeof BusinessInfoRoute
  '/checkout': typeof CheckoutRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/comparar': typeof CompararRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRoute
  '/garantia': typeof GarantiaRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRoute
  '/painel': typeof PainelRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lead/$id': typeof LeadIdRoute
  '/planos/$slug': typeof PlanosSlugRoute
  '/projeto/$id': typeof ProjetoIdRoute
  '/dev/': typeof DevIndexRoute
  '/planos/': typeof PlanosIndexRoute
  '/api/public/notify-admin-signup': typeof ApiPublicNotifyAdminSignupRoute
  '/dev/modelos/$slug': typeof DevModelosSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/dev/modelos/': typeof DevModelosIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-info'
    | '/checkout'
    | '/como-funciona'
    | '/comparar'
    | '/console'
    | '/docs'
    | '/garantia'
    | '/login'
    | '/modelos'
    | '/painel'
    | '/payment-failed'
    | '/payment-success'
    | '/privacidade'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/suporte'
    | '/termos'
    | '/unsubscribe'
    | '/verify-email'
    | '/email/unsubscribe'
    | '/lead/$id'
    | '/planos/$slug'
    | '/projeto/$id'
    | '/dev/'
    | '/planos/'
    | '/api/public/notify-admin-signup'
    | '/dev/modelos/$slug'
    | '/lovable/email/suppression'
    | '/dev/modelos/'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-info'
    | '/checkout'
    | '/como-funciona'
    | '/comparar'
    | '/console'
    | '/docs'
    | '/garantia'
    | '/login'
    | '/modelos'
    | '/painel'
    | '/payment-failed'
    | '/payment-success'
    | '/privacidade'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/suporte'
    | '/termos'
    | '/unsubscribe'
    | '/verify-email'
    | '/email/unsubscribe'
    | '/lead/$id'
    | '/planos/$slug'
    | '/projeto/$id'
    | '/dev'
    | '/planos'
    | '/api/public/notify-admin-signup'
    | '/dev/modelos/$slug'
    | '/lovable/email/suppression'
    | '/dev/modelos'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/business-info'
    | '/checkout'
    | '/como-funciona'
    | '/comparar'
    | '/console'
    | '/docs'
    | '/garantia'
    | '/login'
    | '/modelos'
    | '/painel'
    | '/payment-failed'
    | '/payment-success'
    | '/privacidade'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/suporte'
    | '/termos'
    | '/unsubscribe'
    | '/verify-email'
    | '/email/unsubscribe'
    | '/lead/$id'
    | '/planos/$slug'
    | '/projeto/$id'
    | '/dev/'
    | '/planos/'
    | '/api/public/notify-admin-signup'
    | '/dev/modelos/$slug'
    | '/lovable/email/suppression'
    | '/dev/modelos/'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessInfoRoute: typeof BusinessInfoRoute
  CheckoutRoute: typeof CheckoutRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CompararRoute: typeof CompararRoute
  ConsoleRoute: typeof ConsoleRoute
  DocsRoute: typeof DocsRoute
  GarantiaRoute: typeof GarantiaRoute
  LoginRoute: typeof LoginRoute
  ModelosRoute: typeof ModelosRoute
  PainelRoute: typeof PainelRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LeadIdRoute: typeof LeadIdRoute
  PlanosSlugRoute: typeof PlanosSlugRoute
  ProjetoIdRoute: typeof ProjetoIdRoute
  DevIndexRoute: typeof DevIndexRoute
  PlanosIndexRoute: typeof PlanosIndexRoute
  ApiPublicNotifyAdminSignupRoute: typeof ApiPublicNotifyAdminSignupRoute
  DevModelosSlugRoute: typeof DevModelosSlugRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  DevModelosIndexRoute: typeof DevModelosIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantia': {
      id: '/garantia'
      path: '/garantia'
      fullPath: '/garantia'
      preLoaderRoute: typeof GarantiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-info': {
      id: '/business-info'
      path: '/business-info'
      fullPath: '/business-info'
      preLoaderRoute: typeof BusinessInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/': {
      id: '/planos/'
      path: '/planos'
      fullPath: '/planos/'
      preLoaderRoute: typeof PlanosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto/$id': {
      id: '/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof ProjetoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/$slug': {
      id: '/planos/$slug'
      path: '/planos/$slug'
      fullPath: '/planos/$slug'
      preLoaderRoute: typeof PlanosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead/$id': {
      id: '/lead/$id'
      path: '/lead/$id'
      fullPath: '/lead/$id'
      preLoaderRoute: typeof LeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/modelos/': {
      id: '/dev/modelos/'
      path: '/dev/modelos'
      fullPath: '/dev/modelos/'
      preLoaderRoute: typeof DevModelosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/modelos/$slug': {
      id: '/dev/modelos/$slug'
      path: '/dev/modelos/$slug'
      fullPath: '/dev/modelos/$slug'
      preLoaderRoute: typeof DevModelosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-admin-signup': {
      id: '/api/public/notify-admin-signup'
      path: '/api/public/notify-admin-signup'
      fullPath: '/api/public/notify-admin-signup'
      preLoaderRoute: typeof ApiPublicNotifyAdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessInfoRoute: BusinessInfoRoute,
  CheckoutRoute: CheckoutRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CompararRoute: CompararRoute,
  ConsoleRoute: ConsoleRoute,
  DocsRoute: DocsRoute,
  GarantiaRoute: GarantiaRoute,
  LoginRoute: LoginRoute,
  ModelosRoute: ModelosRoute,
  PainelRoute: PainelRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LeadIdRoute: LeadIdRoute,
  PlanosSlugRoute: PlanosSlugRoute,
  ProjetoIdRoute: ProjetoIdRoute,
  DevIndexRoute: DevIndexRoute,
  PlanosIndexRoute: PlanosIndexRoute,
  ApiPublicNotifyAdminSignupRoute: ApiPublicNotifyAdminSignupRoute,
  DevModelosSlugRoute: DevModelosSlugRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  DevModelosIndexRoute: DevModelosIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
